version: "3.8"

services:
  back-end:
    build: ./back-end
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
    ports:
      - 4000:4000
    volumes:
      - ./back-end:/app
      - /app/node_modules

  file-hosting:
    build: ./file-hosting
    ports:
      - 5001:5001
    volumes:
      - ./file-hosting:/app
      - /app/node_modules

  web-app:
    build: ./web-app
    ports:
      - 3000:3000
    volumes:
      - ./web-app:/app
      - /app/node_modules

  database:
    image: postgres:15
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  database-data:
